### PR TITLE
Support missing args in WaveformBuild

### PR DESCRIPTION
**Pull request by sanmut**
Add more Waveform test

### CODE REVIEW

**Comment by spathiwa** [comment]
Looks good.

**Comment by cglzaguilar** [comment]
Looks good to me too. But I would use the term unwired parameters rather than missing arguments.

**Comment by spathiwa** [comment]
Actually, since Vireo is really its own language, missing (or optional) arguments is the better term.
Vireo doesn't have wires.

**Comment by sanmut** [comment]
Is "wildcard argument" the Vireo terminology for this?

**Comment by spathiwa** [comment]
It's called that at least in the macro defining a symbol name for the '*' string, but I think 'default argument' is used more.

**Pull request merged**
