### PR TITLE
Refactor cpp files

### PR DESCRIPTION
**Pull request by mehagar**
This is a sampling of the kinds of refactoring that Resharper can easily find.

### CODE REVIEW

**Comment by cglzaguilar** [comment]
For the next round of fixing, is it possible to focus on one type of warning? like for example unused variables, so we know the refactor is only about that.

**Comment by rajsite** [comment]
Wonder if we can implement a more thorough linter like clang-tidy on the CI to keep it clean: http://clang.llvm.org/extra/clang-tidy/

Or enabling more gcc warnings. Pretty sure no unused variables is an option amongst others.

**Comment by mehagar** [comment]
> For the next round of fixing, is it possible to focus on one type of warning? like for example unused variables, so we know the refactor is only about that.

Yeah, I can do that.

**Comment by mehagar** [comment]
> Wonder if we can implement a more thorough linter like clang-tidy on the CI to keep it clean: [http://clang.llvm.org/extra/clang-tidy](http://clang.llvm.org/extra/clang-tidy/)
> 
> Or enabling more gcc warnings. Pretty sure no unused variables is an option amongst others.
> 
> Might be a good Prime Day project.

Resharper uses clang-tidy for some of its suggestions. Once I fix the existing warnings I would like to enable this on the CI.

**Pull request merged**
