### PR TITLE
Use provided url parameter in makeSyncRequest

### PR DESCRIPTION
**Pull request by rajsite**

### CODE REVIEW

**Comment by sanmut** [comment]
Appveyor seems to be failing. Is this due to this change?

**Comment by rajsite** [comment]
Looking at the logs the build just stopped in the middle of running Vireo native https://ci.appveyor.com/api/buildjobs/4ryvhl4wj3alg1b9/log

**Comment by rajsite** [comment]
Restarted the AppVeyor build, guess we will see what happens. I'm pretty sure I've seen this behavior before too with the native windows debug builds.

**Comment by sanmut** [comment]
oh ok, thanks.

**Pull request merged**
