### PR TITLE
Armadillo patch1

### PR DESCRIPTION
**Pull request by rajsite**
*targeting the armadillo-patch1 branch, not master*

Cherry-picked the following commits:

da7772d2f70c45e66c5c1bf64a6e636d46c3293f
375a5543c4587ef80249e9e922629f18f5d97bec
8bd4c432b38090f9025516a1a0b01157ea368a3b
dd9910c978099516a8a504732f8ea2eb7932ad83
83e1f4910840908812bfd88827bfdbccb82a5a92
13148b273812d4c47f0429d8a44417c88f176b95

001549ae21a5a79376f6bb581b68de1ce4637eea
4e1bc8be7c2914a40799363c8f62db32acbae7cf

### CODE REVIEW

**Comment by rajsite** [comment]
@cglzaguilar Attached is a build of Vireo with these changes if you wanted to test it against Ray's example before approving the pull request

[vireo-7.2.2.zip](https://github.com/ni/VireoSDK/files/1841752/vireo-7.2.2.zip)

**Comment by sanmut** [comment]
The following commit is not needed and we should exclude it for a patch release. Not tested enough and not worth the risk.
Move userShell into separate scope than root shell  … 2b96989

What is the following commit? Does it exist on the master?
Handle npm 5.6.0 package-lock changes  … 857208f

**Comment by sanmut** [comment]
Is the branch short-lived only for reviews and are we going to delete it after creating and pushing tags? If so, it is ok. If not, I will create the branch name as ni/releases/armadillo-patch1 or ni/releases/patches/armadillo-patch1

**Comment by rajsite** [comment]
Closing to recreate the pull request without commit https://github.com/ni/VireoSDK/commit/83e1f4910840908812bfd88827bfdbccb82a5a92

**Comment by rajsite** [comment]
Talked to sankara and for the other questions.
The npm package-lock.json change just effects when npm run scripts are executed locally and does not even get included in a built package. 
The branch is short lived and will be deleted, the tagged release is what matters.

**Pull request closed without merging**
