### PR TITLE
Remove Write to system log API from Vireo

### PR DESCRIPTION
**Pull request by MalleshSushmitha**
The Write to system log API for the Vireo target is now built using JSLI in the NXG code base(it was previously using an SLI). 
So we no longer need this function definition in the Vireo code base. 

Note: 
I have also removed the tests related to the same function.
PR for changes on the NXG codebase: [PR](https://ni.visualstudio.com/DevCentral/_git/ASW/pullrequest/198533)

### CODE REVIEW

**Comment by rajsite** [comment]
@MalleshSushmitha is there a reason this was changed to a Draft PR? Is it not ready for review?

**Comment by MalleshSushmitha** [comment]
> @MalleshSushmitha is there a reason this was changed to a Draft PR? Is it not ready for review?

I was not aware that owners will be added as soon as I create a PR here. I changed it to draft since I haven't gotten this reviewed locally by anyone in the team.

**Comment by rajsite** [comment]
@MalleshSushmitha Thanks for clarifying. Just making sure it was intentional. Will review when it is changed out of draft 👍

**Review by ansujay — APPROVED** [review]

**Comment by MalleshSushmitha** [comment]
> @MalleshSushmitha Thanks for clarifying. Just making sure it was intentional. Will review when it is changed out of draft 👍

@rajsite This is ready for review now.

**Comment by rajsite** [comment]
@MalleshSushmitha sorry for the delay, I expect to review this tomorrow

**Comment by sanmut** [comment]
@MalleshSushmitha , would you mind referencing the NXG side commits/PRs that implement the feature for reference?

**Comment by MalleshSushmitha** [comment]
@sanmut I have modified to include a link to the PR in the description.

**Review by sanmut — APPROVED** [review]

**Review by rajsite — APPROVED** [review]

**Comment by rajsite** [comment]
Bypassing @cglzaguilar and @spathiwa who are required reviewers but this is a pretty simple change that effectively reverts https://github.com/ni/VireoSDK/pull/570

**Comment by rajsite** [comment]
@MalleshSushmitha A new Vireo was released with thee changes. Make sure to [update Vireo in ASW](https://ni.visualstudio.com/DevCentral/_wiki/wikis/AppCentral.wiki/2445/How-to-update-Vireo-in-NXG).

**Pull request merged**
