### PR TITLE
Upgrade emsdk version to sdk-1.37.36-64bit

### LINKED ISSUE #362: Emscripten versioning and notes
Currently using:
On travis 1.37.0 (not sure if this is accurate, retrieved from travis build)
On AppVeyor 1.37.9

Changes to be aware of:
1.37.27 moves the functions on the [Runtime object](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-does-runtime-no-longer-exist-why-do-i-get-an-error-trying-to-access-runtime-something) which are APIs [we use](https://github.com/ni/VireoSDK/search?l=JavaScript&q=Module.Runtime&type=&utf8=%E2%9C%93).

May be possible to use shipping emsdk binaries on Travis: https://github.com/kripken/emscripten/pull/5087#issuecomment-320124568

Emscripten is using Xenial from Docker:
https://github.com/kripken/emscripten/pull/5614

Might wait for Travis to use Xenial:
https://github.com/travis-ci/travis-ci/issues/7260

### PR DESCRIPTION
**Pull request by rajsite**
- Upgrade emsdk version for Travis and AppVeyor
- Make JS source changes to move Module.Runtime calls to Module based on emscripten api changes. Fixes #362 
- Add EM_RUNTIME_EXPORTS to prevent DCE of needed runtime functions
-  Update the README Vireo setup, build, and test docs

### CODE REVIEW

**Comment by cglzaguilar** [comment]
Please let us know the results of the LVjs CI and any performance testing you do as we discussed.

**Comment by rajsite** [comment]
Working on the LVjs CI and will do the ASW JS benchmark suite. It has peek and poke perf tests as well as the PI Calc perf test

**Comment by rajsite** [comment]
compiler_upgrade_perf

[Results.csv.txt](https://github.com/ni/VireoSDK/files/1908413/Results.csv.txt)

**Comment by rajsite** [comment]
LVjs CI behaving as expected (several tests "not executed" and some unrelated SCT failures)

**Comment by rajsite** [comment]
@sanmut any concerns with the benchmarks before I merge? Nothing looked terribly interesting to me

**Comment by rajsite** [comment]
To me the most telling test is that the PiCalc benchmark had effectively no change. All the peek and poke tests are stressing the JS / C++ interface which is already more volatile with object allocations and GC pressure.

**Comment by rajsite** [comment]
Pushing more benchmarks here. These are from after the vireo api refactor.
[Results.xlsx](https://github.com/ni/VireoSDK/files/2255638/Results.xlsx)

**Pull request merged**
