### PR TITLE
Update Makefiles (including AAL support), fix nfs-run-tests abort and fix a bug in Search1DArray

### PR DESCRIPTION
**Pull request by spathiwa**

### CODE REVIEW

**Comment by cglzaguilar** [comment]
Hi Craig, please sync to the latest Vireo, and resolve the conflicts. The pull request has conflicts that can not be resolved automatically.

**Comment by spathiwa** [comment]
I saw that it said that on the pull request but I could not find where it says what the conflicts are.

I am already at the latest Vireo and do not have any local conflicts.

[zifmia:~/dev/VireoSDK]% git pull
Already up-to-date.
[zifmia:~/dev/VireoSDK]% git status
On branch incoming
Your branch is up-to-date with 'origin/incoming'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dist/vireo.js

no changes added to commit (use "git add" and/or "git commit -a")
[zifmia:~/dev/VireoSDK]% 

Not sure what to do to resolve this.

**Comment by spathiwa** [comment]
Can you just do the pull and see what conflicts it says then?

**Comment by cglzaguilar** [comment]
Your branch is OK, you need to update your branch from the main Vireo repository and then fix the conflicts.

Here are the steps that I do from the command line:

1. Do a : git remote -v
2. If the ni Vireo upstream is not there add it: git remote add upstream https://github.com/ni/VireoSDK.git
3. Do the following to get the latest changes from ni/VireoSDK: git pull upstream incoming

**Pull request closed without merging**
